pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(
                    branches: [[name: '*/master']],
                    extensions: [],
                    userRemoteConfigs: [[url: 'https://github.com/Andherson333333/pruebaGit']]
                )
            }
        }

        stage('Test') {
            steps {
                sh '''
                    node --version
                    git --version
                    curl --version
                '''
            }
        }
    }
}
