pipeline {
    agent any

    stages {
        stage('Construir Imagen Docker') {
            steps {
                script {
                    // Construir la imagen Docker utilizando el Dockerfile
                    docker.build('nginx-web', '-f Dockerfile .')
                }
            }
        }

        stage('Desplegar en Nginx') {
            steps {
                script {
                    // Ejecutar un contenedor Docker de Nginx y desplegar la página web
                    docker.image('nginx-web').withRun('-p 8080:80') {
                        // No es necesario copiar los archivos aquí, ya que el Dockerfile debe manejarlo
                    }
                }
            }
        }
    }
}


